# Generated by Django 4.2 on 2023-04-10 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SusPerson",
            fields=[
                (
                    "player_id",
                    models.CharField(
                        help_text="Player id from The Tower, pk",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Player's friendly name, e.g. common discord handle",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional comments",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "sus",
                    models.BooleanField(default=True, help_text="Is the person sus?"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSusPerson",
            fields=[
                (
                    "player_id",
                    models.CharField(
                        db_index=True,
                        help_text="Player id from The Tower, pk",
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Player's friendly name, e.g. common discord handle",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional comments",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "sus",
                    models.BooleanField(default=True, help_text="Is the person sus?"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sus person",
                "verbose_name_plural": "historical sus persons",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
