# Generated by Django 4.2 on 2023-05-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0003_populate_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsusperson",
            name="banned",
            field=models.BooleanField(
                default=False, help_text="Banned by Pog. For internal use."
            ),
        ),
        migrations.AddField(
            model_name="susperson",
            name="banned",
            field=models.BooleanField(
                default=False, help_text="Banned by Pog. For internal use."
            ),
        ),
        migrations.AlterField(
            model_name="historicalsusperson",
            name="sus",
            field=models.BooleanField(
                default=True,
                help_text="Is the person sus? if checked, they will be removed from the results on the public website.",
            ),
        ),
        migrations.AlterField(
            model_name="playerid",
            name="player",
            field=models.ForeignKey(
                help_text="Player",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ids",
                to="sus.knownplayer",
            ),
        ),
        migrations.AlterField(
            model_name="susperson",
            name="sus",
            field=models.BooleanField(
                default=True,
                help_text="Is the person sus? if checked, they will be removed from the results on the public website.",
            ),
        ),
    ]
