# Generated by Django 4.2 on 2023-06-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0005_knownplayer_discord_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="knownplayer",
            name="approved",
            field=models.BooleanField(
                default=False, help_text="Has this entry been validated?"
            ),
        ),
    ]
