# Generated by Django 4.2 on 2023-06-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0007_populate_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knownplayer",
            name="approved",
            field=models.BooleanField(
                default=True, help_text="Has this entry been validated?"
            ),
        ),
    ]
