# Generated by Django 4.2 on 2023-07-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sus", "0008_alter_knownplayer_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsusperson",
            name="banned",
        ),
        migrations.RemoveField(
            model_name="susperson",
            name="banned",
        ),
        migrations.AddField(
            model_name="historicalsusperson",
            name="soft_banned",
            field=models.BooleanField(
                default=False, help_text="Soft-banned by Pog. For internal use."
            ),
        ),
        migrations.AddField(
            model_name="susperson",
            name="soft_banned",
            field=models.BooleanField(
                default=False, help_text="Soft-banned by Pog. For internal use."
            ),
        ),
    ]
