# Generated by Django 4.2 on 2023-07-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sus", "0009_remove_historicalsusperson_banned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsusperson",
            name="banned",
            field=models.BooleanField(
                default=False, help_text="Banned by support. For internal use."
            ),
        ),
        migrations.AddField(
            model_name="susperson",
            name="banned",
            field=models.BooleanField(
                default=False, help_text="Banned by support. For internal use."
            ),
        ),
    ]
