# Generated by Django 4.2.7 on 2023-11-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sus", "0010_historicalsusperson_banned_susperson_banned"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviewed",
            fields=[
                (
                    "player_id",
                    models.CharField(
                        help_text="Player id from The Tower, pk",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
