# Generated by Django 4.2.7 on 2024-01-24 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sus", "0011_reviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsusperson",
            name="created",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalsusperson",
            name="modified",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="susperson",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="susperson",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
