# Generated by Django 5.0.6 on 2024-10-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0014_historicalknownplayer_historicalplayerid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="susperson",
            options={"ordering": ("modified",)},
        ),
    ]
