# Generated by Django 5.0.6 on 2024-10-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sus", "0015_alter_susperson_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="susperson",
            options={"ordering": ("-modified",)},
        ),
    ]
